package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accreditation generated by hbm2java
 */
@Entity
@Table(name="accreditation"
    ,catalog="appsport"
)
public class Accreditation  implements java.io.Serializable {


     private Integer idaccreditation;
     private Competition competition;
     private Discipline discipline;
     private Individu individu;
     private StatutAccreditation statutAccreditation;
     private String matricule;

    public Accreditation() {
    }

    public Accreditation(Competition competition, Discipline discipline, Individu individu, StatutAccreditation statutAccreditation, String matricule) {
       this.competition = competition;
       this.discipline = discipline;
       this.individu = individu;
       this.statutAccreditation = statutAccreditation;
       this.matricule = matricule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaccreditation", unique=true, nullable=false)
    public Integer getIdaccreditation() {
        return this.idaccreditation;
    }
    
    public void setIdaccreditation(Integer idaccreditation) {
        this.idaccreditation = idaccreditation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcompetition")
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddiscipline")
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu")
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idstatut")
    public StatutAccreditation getStatutAccreditation() {
        return this.statutAccreditation;
    }
    
    public void setStatutAccreditation(StatutAccreditation statutAccreditation) {
        this.statutAccreditation = statutAccreditation;
    }

    
    @Column(name="matricule", length=45)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }




}


