package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AthleteDiscipline generated by hbm2java
 */
@Entity
@Table(name="athlete_discipline"
    ,catalog="appsport"
)
public class AthleteDiscipline  implements java.io.Serializable {


     private Integer idathleteDiscipline;
     private Athlete athlete;
     private Categorie categorie;
     private Discipline discipline;

    public AthleteDiscipline() {
    }

    public AthleteDiscipline(Athlete athlete, Categorie categorie, Discipline discipline) {
       this.athlete = athlete;
       this.categorie = categorie;
       this.discipline = discipline;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idathlete_discipline", unique=true, nullable=false)
    public Integer getIdathleteDiscipline() {
        return this.idathleteDiscipline;
    }
    
    public void setIdathleteDiscipline(Integer idathleteDiscipline) {
        this.idathleteDiscipline = idathleteDiscipline;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idathlete")
    public Athlete getAthlete() {
        return this.athlete;
    }
    
    public void setAthlete(Athlete athlete) {
        this.athlete = athlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategorie")
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddiscipline")
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }




}


