package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Athlete generated by hbm2java
 */
@Entity
@Table(name="athlete"
    ,catalog="appsport"
)
public class Athlete  implements java.io.Serializable {


     private Integer idathlete;
     private Individu individu;
     private Organisation organisation;
     private String matricule;
     private String statut;
     private Set<AthleteDiscipline> athleteDisciplines = new HashSet<AthleteDiscipline>(0);

    public Athlete() {
    }

    public Athlete(Individu individu, Organisation organisation, String matricule, String statut, Set<AthleteDiscipline> athleteDisciplines) {
       this.individu = individu;
       this.organisation = organisation;
       this.matricule = matricule;
       this.statut = statut;
       this.athleteDisciplines = athleteDisciplines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idathlete", unique=true, nullable=false)
    public Integer getIdathlete() {
        return this.idathlete;
    }
    
    public void setIdathlete(Integer idathlete) {
        this.idathlete = idathlete;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu")
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idorganisation")
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    
    @Column(name="matricule", length=45)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="athlete")
    public Set<AthleteDiscipline> getAthleteDisciplines() {
        return this.athleteDisciplines;
    }
    
    public void setAthleteDisciplines(Set<AthleteDiscipline> athleteDisciplines) {
        this.athleteDisciplines = athleteDisciplines;
    }




}


