package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="appsport"
)
public class Categorie  implements java.io.Serializable {


     private Integer idcategorie;
     private Discipline discipline;
     private String code;
     private String libelle;
     private Set<Individu> individus = new HashSet<Individu>(0);
     private Set<AthleteDiscipline> athleteDisciplines = new HashSet<AthleteDiscipline>(0);

    public Categorie() {
    }

    public Categorie(Discipline discipline, String code, String libelle, Set<Individu> individus, Set<AthleteDiscipline> athleteDisciplines) {
       this.discipline = discipline;
       this.code = code;
       this.libelle = libelle;
       this.individus = individus;
       this.athleteDisciplines = athleteDisciplines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcategorie", unique=true, nullable=false)
    public Integer getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(Integer idcategorie) {
        this.idcategorie = idcategorie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddiscipline")
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
    public Set<Individu> getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set<Individu> individus) {
        this.individus = individus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
    public Set<AthleteDiscipline> getAthleteDisciplines() {
        return this.athleteDisciplines;
    }
    
    public void setAthleteDisciplines(Set<AthleteDiscipline> athleteDisciplines) {
        this.athleteDisciplines = athleteDisciplines;
    }




}


