package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name="competition"
    ,catalog="appsport"
)
public class Competition  implements java.io.Serializable {


     private Integer idcompetition;
     private String code;
     private String libelle;
     private Date dateDebut;
     private Date dateFin;
     private Date dateFinAccreditation;
     private Date dateDebutAccreditation;
     private String statut;
     private Boolean encours;
     private Set<Accreditation> accreditations = new HashSet<Accreditation>(0);

    public Competition() {
    }

    public Competition(String code, String libelle, Date dateDebut, Date dateFin, Date dateFinAccreditation, Date dateDebutAccreditation, String statut, Boolean encours, Set<Accreditation> accreditations) {
       this.code = code;
       this.libelle = libelle;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.dateFinAccreditation = dateFinAccreditation;
       this.dateDebutAccreditation = dateDebutAccreditation;
       this.statut = statut;
       this.encours = encours;
       this.accreditations = accreditations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcompetition", unique=true, nullable=false)
    public Integer getIdcompetition() {
        return this.idcompetition;
    }
    
    public void setIdcompetition(Integer idcompetition) {
        this.idcompetition = idcompetition;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin_accreditation", length=19)
    public Date getDateFinAccreditation() {
        return this.dateFinAccreditation;
    }
    
    public void setDateFinAccreditation(Date dateFinAccreditation) {
        this.dateFinAccreditation = dateFinAccreditation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut_accreditation", length=19)
    public Date getDateDebutAccreditation() {
        return this.dateDebutAccreditation;
    }
    
    public void setDateDebutAccreditation(Date dateDebutAccreditation) {
        this.dateDebutAccreditation = dateDebutAccreditation;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="encours")
    public Boolean getEncours() {
        return this.encours;
    }
    
    public void setEncours(Boolean encours) {
        this.encours = encours;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competition")
    public Set<Accreditation> getAccreditations() {
        return this.accreditations;
    }
    
    public void setAccreditations(Set<Accreditation> accreditations) {
        this.accreditations = accreditations;
    }




}


