package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discipline generated by hbm2java
 */
@Entity
@Table(name="discipline"
    ,catalog="appsport"
)
public class Discipline  implements java.io.Serializable {


     private Integer iddiscipline;
     private String code;
     private String libelle;
     private Set<AthleteDiscipline> athleteDisciplines = new HashSet<AthleteDiscipline>(0);
     private Set<Categorie> categories = new HashSet<Categorie>(0);
     private Set<IndividuDiscipline> individuDisciplines = new HashSet<IndividuDiscipline>(0);
     private Set<Accreditation> accreditations = new HashSet<Accreditation>(0);

    public Discipline() {
    }

    public Discipline(String code, String libelle, Set<AthleteDiscipline> athleteDisciplines, Set<Categorie> categories, Set<IndividuDiscipline> individuDisciplines, Set<Accreditation> accreditations) {
       this.code = code;
       this.libelle = libelle;
       this.athleteDisciplines = athleteDisciplines;
       this.categories = categories;
       this.individuDisciplines = individuDisciplines;
       this.accreditations = accreditations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddiscipline", unique=true, nullable=false)
    public Integer getIddiscipline() {
        return this.iddiscipline;
    }
    
    public void setIddiscipline(Integer iddiscipline) {
        this.iddiscipline = iddiscipline;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discipline")
    public Set<AthleteDiscipline> getAthleteDisciplines() {
        return this.athleteDisciplines;
    }
    
    public void setAthleteDisciplines(Set<AthleteDiscipline> athleteDisciplines) {
        this.athleteDisciplines = athleteDisciplines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discipline")
    public Set<Categorie> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Categorie> categories) {
        this.categories = categories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discipline")
    public Set<IndividuDiscipline> getIndividuDisciplines() {
        return this.individuDisciplines;
    }
    
    public void setIndividuDisciplines(Set<IndividuDiscipline> individuDisciplines) {
        this.individuDisciplines = individuDisciplines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discipline")
    public Set<Accreditation> getAccreditations() {
        return this.accreditations;
    }
    
    public void setAccreditations(Set<Accreditation> accreditations) {
        this.accreditations = accreditations;
    }




}


