package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Individu generated by hbm2java
 */
@Entity
@Table(name="individu"
    ,catalog="appsport"
)
public class Individu  implements java.io.Serializable {


     private Integer idindividu;
     private Categorie categorie;
     private IndividuPhoto individuPhoto;
     private Organisation organisation;
     private Qualite qualite;
     private Region region;
     private StatutAccreditation statutAccreditation;
     private String nom;
     private String prenom;
     private String surnom;
     private Date datenaiss;
     private Integer taille;
     private Integer poids;
     private String tel;
     private String email;
     private String matricule;
     private Integer iddiscipline;
     private Boolean genre;
     private byte[] imageAntiDopage;
     private String statut;
     private String lieunaiss;
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Athlete> athletes = new HashSet<Athlete>(0);
     private Set<IndividuDiscipline> individuDisciplines = new HashSet<IndividuDiscipline>(0);
     private Set<Accreditation> accreditations = new HashSet<Accreditation>(0);

    public Individu() {
    }

    public Individu(Categorie categorie, IndividuPhoto individuPhoto, Organisation organisation, Qualite qualite, Region region, StatutAccreditation statutAccreditation, String nom, String prenom, String surnom, Date datenaiss, Integer taille, Integer poids, String tel, String email, String matricule, Integer iddiscipline, Boolean genre, byte[] imageAntiDopage, String statut, String lieunaiss, Set<Staff> staffs, Set<Athlete> athletes, Set<IndividuDiscipline> individuDisciplines, Set<Accreditation> accreditations) {
       this.categorie = categorie;
       this.individuPhoto = individuPhoto;
       this.organisation = organisation;
       this.qualite = qualite;
       this.region = region;
       this.statutAccreditation = statutAccreditation;
       this.nom = nom;
       this.prenom = prenom;
       this.surnom = surnom;
       this.datenaiss = datenaiss;
       this.taille = taille;
       this.poids = poids;
       this.tel = tel;
       this.email = email;
       this.matricule = matricule;
       this.iddiscipline = iddiscipline;
       this.genre = genre;
       this.imageAntiDopage = imageAntiDopage;
       this.statut = statut;
       this.lieunaiss = lieunaiss;
       this.staffs = staffs;
       this.athletes = athletes;
       this.individuDisciplines = individuDisciplines;
       this.accreditations = accreditations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idindividu", unique=true, nullable=false)
    public Integer getIdindividu() {
        return this.idindividu;
    }
    
    public void setIdindividu(Integer idindividu) {
        this.idindividu = idindividu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategorie")
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idphoto")
    public IndividuPhoto getIndividuPhoto() {
        return this.individuPhoto;
    }
    
    public void setIndividuPhoto(IndividuPhoto individuPhoto) {
        this.individuPhoto = individuPhoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idorganisation")
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idqualite")
    public Qualite getQualite() {
        return this.qualite;
    }
    
    public void setQualite(Qualite qualite) {
        this.qualite = qualite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregion")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idstatut_accreditation")
    public StatutAccreditation getStatutAccreditation() {
        return this.statutAccreditation;
    }
    
    public void setStatutAccreditation(StatutAccreditation statutAccreditation) {
        this.statutAccreditation = statutAccreditation;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=45)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="surnom", length=45)
    public String getSurnom() {
        return this.surnom;
    }
    
    public void setSurnom(String surnom) {
        this.surnom = surnom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datenaiss", length=10)
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }

    
    @Column(name="taille")
    public Integer getTaille() {
        return this.taille;
    }
    
    public void setTaille(Integer taille) {
        this.taille = taille;
    }

    
    @Column(name="poids")
    public Integer getPoids() {
        return this.poids;
    }
    
    public void setPoids(Integer poids) {
        this.poids = poids;
    }

    
    @Column(name="tel", length=45)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="matricule", length=45)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    
    @Column(name="iddiscipline")
    public Integer getIddiscipline() {
        return this.iddiscipline;
    }
    
    public void setIddiscipline(Integer iddiscipline) {
        this.iddiscipline = iddiscipline;
    }

    
    @Column(name="genre")
    public Boolean getGenre() {
        return this.genre;
    }
    
    public void setGenre(Boolean genre) {
        this.genre = genre;
    }

    
    @Column(name="image_anti_dopage")
    public byte[] getImageAntiDopage() {
        return this.imageAntiDopage;
    }
    
    public void setImageAntiDopage(byte[] imageAntiDopage) {
        this.imageAntiDopage = imageAntiDopage;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="lieunaiss", length=45)
    public String getLieunaiss() {
        return this.lieunaiss;
    }
    
    public void setLieunaiss(String lieunaiss) {
        this.lieunaiss = lieunaiss;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Athlete> getAthletes() {
        return this.athletes;
    }
    
    public void setAthletes(Set<Athlete> athletes) {
        this.athletes = athletes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<IndividuDiscipline> getIndividuDisciplines() {
        return this.individuDisciplines;
    }
    
    public void setIndividuDisciplines(Set<IndividuDiscipline> individuDisciplines) {
        this.individuDisciplines = individuDisciplines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="individu")
    public Set<Accreditation> getAccreditations() {
        return this.accreditations;
    }
    
    public void setAccreditations(Set<Accreditation> accreditations) {
        this.accreditations = accreditations;
    }




}


