package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IndividuDiscipline generated by hbm2java
 */
@Entity
@Table(name="individu_discipline"
    ,catalog="appsport"
)
public class IndividuDiscipline  implements java.io.Serializable {


     private Integer idindividuDiscipline;
     private Discipline discipline;
     private Individu individu;

    public IndividuDiscipline() {
    }

    public IndividuDiscipline(Discipline discipline, Individu individu) {
       this.discipline = discipline;
       this.individu = individu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idindividu_discipline", unique=true, nullable=false)
    public Integer getIdindividuDiscipline() {
        return this.idindividuDiscipline;
    }
    
    public void setIdindividuDiscipline(Integer idindividuDiscipline) {
        this.idindividuDiscipline = idindividuDiscipline;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddiscipline")
    public Discipline getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu")
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }




}


