package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name="organisation"
    ,catalog="appsport"
)
public class Organisation  implements java.io.Serializable {


     private Integer idorganisation;
     private Region region;
     private String code;
     private String libelle;
     private Set<Athlete> athletes = new HashSet<Athlete>(0);
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
     private Set<Individu> individus = new HashSet<Individu>(0);

    public Organisation() {
    }

    public Organisation(Region region, String code, String libelle, Set<Athlete> athletes, Set<Utilisateur> utilisateurs, Set<Individu> individus) {
       this.region = region;
       this.code = code;
       this.libelle = libelle;
       this.athletes = athletes;
       this.utilisateurs = utilisateurs;
       this.individus = individus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idorganisation", unique=true, nullable=false)
    public Integer getIdorganisation() {
        return this.idorganisation;
    }
    
    public void setIdorganisation(Integer idorganisation) {
        this.idorganisation = idorganisation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregion")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Athlete> getAthletes() {
        return this.athletes;
    }
    
    public void setAthletes(Set<Athlete> athletes) {
        this.athletes = athletes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Individu> getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set<Individu> individus) {
        this.individus = individus;
    }




}


