package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Qualite generated by hbm2java
 */
@Entity
@Table(name="qualite"
    ,catalog="appsport"
)
public class Qualite  implements java.io.Serializable {


     private Integer idqualite;
     private String code;
     private String libelle;
     private Set<Individu> individus = new HashSet<Individu>(0);

    public Qualite() {
    }

    public Qualite(String code, String libelle, Set<Individu> individus) {
       this.code = code;
       this.libelle = libelle;
       this.individus = individus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idqualite", unique=true, nullable=false)
    public Integer getIdqualite() {
        return this.idqualite;
    }
    
    public void setIdqualite(Integer idqualite) {
        this.idqualite = idqualite;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="qualite")
    public Set<Individu> getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set<Individu> individus) {
        this.individus = individus;
    }




}


