package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name="staff"
    ,catalog="appsport"
)
public class Staff  implements java.io.Serializable {


     private Integer idstaff;
     private Individu individu;
     private Integer idorganisation;
     private Integer idqualite;

    public Staff() {
    }

    public Staff(Individu individu, Integer idorganisation, Integer idqualite) {
       this.individu = individu;
       this.idorganisation = idorganisation;
       this.idqualite = idqualite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstaff", unique=true, nullable=false)
    public Integer getIdstaff() {
        return this.idstaff;
    }
    
    public void setIdstaff(Integer idstaff) {
        this.idstaff = idstaff;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idindividu")
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }

    
    @Column(name="idorganisation")
    public Integer getIdorganisation() {
        return this.idorganisation;
    }
    
    public void setIdorganisation(Integer idorganisation) {
        this.idorganisation = idorganisation;
    }

    
    @Column(name="idqualite")
    public Integer getIdqualite() {
        return this.idqualite;
    }
    
    public void setIdqualite(Integer idqualite) {
        this.idqualite = idqualite;
    }




}


