package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatutAccreditation generated by hbm2java
 */
@Entity
@Table(name="statut_accreditation"
    ,catalog="appsport"
)
public class StatutAccreditation  implements java.io.Serializable {


     private Integer idstatutAccreditation;
     private String code;
     private String libelle;
     private Integer rang;
     private Set<Accreditation> accreditations = new HashSet<Accreditation>(0);
     private Set<Individu> individus = new HashSet<Individu>(0);

    public StatutAccreditation() {
    }

    public StatutAccreditation(String code, String libelle, Integer rang, Set<Accreditation> accreditations, Set<Individu> individus) {
       this.code = code;
       this.libelle = libelle;
       this.rang = rang;
       this.accreditations = accreditations;
       this.individus = individus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idstatut_accreditation", unique=true, nullable=false)
    public Integer getIdstatutAccreditation() {
        return this.idstatutAccreditation;
    }
    
    public void setIdstatutAccreditation(Integer idstatutAccreditation) {
        this.idstatutAccreditation = idstatutAccreditation;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="rang")
    public Integer getRang() {
        return this.rang;
    }
    
    public void setRang(Integer rang) {
        this.rang = rang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statutAccreditation")
    public Set<Accreditation> getAccreditations() {
        return this.accreditations;
    }
    
    public void setAccreditations(Set<Accreditation> accreditations) {
        this.accreditations = accreditations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statutAccreditation")
    public Set<Individu> getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set<Individu> individus) {
        this.individus = individus;
    }




}


