package app.sport.entities;
// Generated 15 mai 2018 16:48:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UtilisateurProfil generated by hbm2java
 */
@Entity
@Table(name="utilisateur_profil"
    ,catalog="appsport"
)
public class UtilisateurProfil  implements java.io.Serializable {


     private Integer idutilisateurProfil;
     private String code;
     private String libelle;
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

    public UtilisateurProfil() {
    }

    public UtilisateurProfil(String code, String libelle, Set<Utilisateur> utilisateurs) {
       this.code = code;
       this.libelle = libelle;
       this.utilisateurs = utilisateurs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idutilisateur_profil", unique=true, nullable=false)
    public Integer getIdutilisateurProfil() {
        return this.idutilisateurProfil;
    }
    
    public void setIdutilisateurProfil(Integer idutilisateurProfil) {
        this.idutilisateurProfil = idutilisateurProfil;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateurProfil")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


